
FREE_PLAN_DURATION_IN_MONTHS = 1
PERSONAL_PLAN_DURATION_IN_MONTHS = 1
PREMIUM_PLAN_DURATION_IN_MONTHS = 3


class PlanCost:
    FREE_PLAN_COST = 0
    MUSIC_PERSONAL = 100
    MUSIC_PREMIUM = 250
    VIDEO_PERSONAL = 200
    VIDEO_PREMIUM = 500
    PODCAST_PERSONAL = 100
    PODCAST_PREMIUM = 300


TOPUP_DURATION_IN_MONTHS = 1


class TopUpCost:
    FOUR_DEVICE = 50
    TEN_DEVICE = 100


RENEWAL_REMINDER_BEFORE_SUBSCRIPTION_EXPIRED_IN_DAYS = 10

DATE_FORMAT = '%d-%m-%Y'
