TIME_FORMAT = "%H:%M"

RACETRACK_ENTRY_TIME = "13:00"
RACETRACK_EXIT_TIME = "20:00"


MINIMUM_BOOKING_TIME_IN_HOURS = 3
FREE_EXTENDED_BOOKING_TIME_IN_MINUTES = 15

EXTENDED_BOOKING_COST_PER_HOUR = 50

HOUR_TO_SECONDS = 3600
MINUTE_TO_SECONDS = 60